from openai import OpenAI
import simplejson as json
import base64
import os
from concurrent.futures import ProcessPoolExecutor
from tqdm import tqdm
from tqdm.contrib.concurrent import process_map
import re
from PIL import Image
import io

system_message = """
  You are an expert-level evaluator for multidisciplinary image editing task. 

    ## Inputs
    - **Original image (First image)**: the image before editing.
    - **Edited image (Second image)**: the image generated by the model.
    - **Ground-truth image (Third image)**: the reference image representing the correct edited result.
    - **Scoring Point**:  several scoring point questions.

    ## Task
    For each scoring point question, evaluate whether the **Edited image (Second image)** satisfies the required condition.
    - Each question must be answered strictly with **"Yes"** or **"No"**.
    - Base your judgment on **visible evidence** from the images.
    - Answer **"Yes"** only if the condition is **clearly satisfied**; otherwise answer **"No"**.

    ## Evaluation Logic (CRITICAL)
    - The **primary evaluation target is the Edited image (Second image)**.
    - The **Original image (First image)** *may be used* to verify whether the **intended edit has been applied**.
    - The **Ground-truth image (Third image)** *may be used* to verify whether the **final result matches the intended correct outcome**.

    ## Istruction
    - For questions that involve **text content**, you do **not** need a character-by-character match. If the text in the Edited image conveys **the same meaning** as in questions (e.g., using the same word or phrase, a singular/plural variant, a common abbreviation, a synonymous wording, or an equivalent mathematical expression), you should treat it as correct.
    - For questions that involve mathematical or geometric relations (such as equality of lengths, perpendicularity, parallelism, collinearity, equal angles, etc.), you only need to check whether the relation visually appears to be satisfied in the Edited image. Small pixel-level inaccuracies can be ignored as long as the relation is visually consistent with the questions.
    - Do **NOT** judge the correctness of positions or geometric relations by reading labels alone; always verify them against the actual drawn locations and shapes in the image.

    ## Output
        For each question, you **MUST** answer **STRICTLY** in JSON Format: [{"question": "repeat the question", "answer":"Yes or No", "reason":"the reason"}].
        Example output:
            [
            {
                "question": "repeat the question",
                "answer": "Yes or No",
                "reason": "the reason"
            },
            {
                "question": "repeat the question",
                "answer": "Yes or No",
                "reason": "the reason"
            }
            ]
        Do NOT wrap the JSON output in markdown code blocks (**no ```json, no ```**).
        Return ONLY a valid **JSON array**.
    """

def encode_image(image_path, target_size=1024, fmt="JPEG"):
    img = Image.open(image_path)
    if img.mode in ('RGBA', 'P'):
        img = img.convert('RGB')
    
    if target_size is not None and target_size > 0:
        w, h = img.size
        if max(w, h) > target_size:
            if w >= h:
                new_w = target_size
                new_h = int(h * target_size / w)
            else:
                new_h = target_size
                new_w = int(w * target_size / h)
            img = img.resize((new_w, new_h), Image.LANCZOS)
        
    img_buffer = io.BytesIO()
    img.save(img_buffer, format=fmt)
    image_data = img_buffer.getvalue()
    return base64.b64encode(image_data).decode('utf-8')

def eval_one(args):
    data, result_json_path, judge, API_CONFIG = args
    client = OpenAI(
                base_url=API_CONFIG["url"],
                api_key=API_CONFIG ["key"]
                )

    raw_ori = data["image_path"]
    raw_edit = data["editing_path"]
    raw_gt = data["gt"]
    questions = []
    scores = []
    for q in data["questions"]:
        questions.append(q["question"])
        scores.append(q["score"])
    
    id = data["task_id"]

    ori = encode_image(raw_ori)
    edit = encode_image(raw_edit)
    gt = encode_image(raw_gt)
    messages =[
        {"role": "system", "content": system_message}, 
        {"role": "user", "content": [
            {"type": "text", "text": "Here is the Original image (First image):"}, 
            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{ori}"}}, 
            {"type": "text", "text": "\n\nHere is the Edited image (Second image):"}, 
            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{edit}"}}, 
            {"type": "text", "text": "\n\nHere is the Ground-truth image (Third image):"},
            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{gt}"}}, 
            *[{"type": "text", "text": f"{q}"} for q in questions]
        ]}
    ]

    flag = 0
    log = {}
    while(flag <= 5):
        try:
            response = client.chat.completions.create(
                                        model=judge,
                                        reasoning_effort= "low",
                                        #temperature=0.0,
                                        messages=messages
                                            )
           
            raw_response = response.choices[0].message.content
            
            pattern = r'^```[a-zA-Z0-9]*\n?(.*?)\n?```$'
            match = re.match(pattern, raw_response, re.DOTALL)  
            if match:
                raw_response = match.group(1).strip()  
            
            score = 0

            
            resp  = json.loads(raw_response)
            for i, item in enumerate(resp):
                item["id"] = id
                item["score"] = scores[i]
                if 'yes' in item["answer"].lower():
                    score  = score + scores[i]
            
            log["vqa"] = resp  
            log["score"] = score
            result_json = os.path.join(result_json_path, f"{data['task_id']}.json")
            
            with open(result_json, 'w',encoding='utf-8') as f:
                json.dump(log, f, indent=4, ensure_ascii=False)
            flag = 10
        except Exception as e:
            print(raw_response)
            print(f"{id}: ", str(e))
            flag += 1
            continue
    if flag == 6:
        print(f"{data['task_id']} reasoning eval fail over 5 time! :( )")
        
    

def reasoning_eval(data_json, judge, non_pass_list, API_CONFIG, WORKERS):
    
    domain = data_json.split('/')[-2]
    result_json = os.path.join(os.path.dirname(data_json), f"{judge[1]}_eval_1")  
    
    os.makedirs(result_json, exist_ok = True)

    with open(data_json, "r", encoding="utf-8") as f:
        datas = json.load(f)
    
    try:
        done_list = []
        for dir, _, files in os.walk(result_json):
            for file in files:
                if file.split('.')[-1] == "json":
                    done_list.append( file.split('.')[0])
        
    except Exception as e:
        done_list = []
    
    data_config = []
    for data in datas:
        if data["task_id"] not in done_list and not data["task_id"] in non_pass_list:
            data_config.append((data, result_json, judge[0], API_CONFIG))

    print(f"number of reasoning eval tasks for {domain}:", len(data_config))
    
    with ProcessPoolExecutor(max_workers=WORKERS) as ex:
        process_map(eval_one, data_config, max_workers=WORKERS)
    print(f"{domain} reasoning eval done")

    return [result_json]
    



